name: CI 
on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: string
            ambient:
                required: true
                type: choice
                options:
                    - staging
                    - production
            auto_rollback:
                required: false
                type: boolean
                default: false
jobs:
    workflow_ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: echo "Fazendo checkout do codigo"
            - name: Build
              run: echo "Fazendo build do codigo"
            - name: Test
              run: echo "Fazendo testes do codigo"
    workflow_cd:
        uses: vinicius3516/githubaction-course/.github/workflows/deploy.yml@main
        needs: workflow_ci
        with:
            ambient: ${{ github.event.inputs.ambient }}
            version: ${{ github.event.inputs.version }}
            auto_rollback: ${{ github.event.inputs.auto_rollback }}
            