name: CI 
on:
    workflow_dispatch:
jobs:
    workflow_ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: echo "Fazendo checkout do codigo"
            - name: Build
              run: echo "Fazendo build do codigo"
            - name: Test
              run: echo "Fazendo testes do codigo"
    workflow_cd:
        uses: vinicius3516/githubaction-course/.github/workflows/deploy.yml@main
        needs: workflow_ci
        with:
            ambient: priduction
            version: v1.0.0
            auto_rollback: true
            