name: CD
on:
    workflow_call:
        inputs:
            ambient:
                required: true
                type: string
            version:
                required: true
                type: string
            auto_rollback:
                required: false
                type: boolean
                default: false

jobs:
    workflow_cd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: echo "Fazendo Deploy do codigo no ambiente de ${{ inputs.ambient }}"
            - name: Version
              run: echo "Fazendo Deploy da versão ${{ inputs.version }}"
